#!/bin/sh

echo "$(figlet Threads-CLI)" 
echo ""
echo "Threads-CLI is a command line tool to grab information about any profile on Threads."
echo ""
echo "- by Amoghavarsha, @TheAmoghavarsha" 
echo ""

echo "Enter the username: "
echo ""
read username

# Construct the URL based on the entered username
url="https://www.threads.net/@${username}"

# Fetch the webpage content and store it in a temporary file
tmp_file=$(mktemp)
curl -s "$url" > "$tmp_file"

# Extract "<something> Followers" from the HTML content
followers=$(grep -oE '[0-9]+[A-Za-z]* Followers' "$tmp_file" | head -n 1)

# Extract "Amoghavarsha (theamoghavarsha)" from the <meta property="og:title"> tag
title=$(grep -o '<meta property="og:title" content="[^"]*' "$tmp_file" | grep -o '[^"]*$' | sed 's/&#064;//g' | sed 's/ on Threads$//')

# Extract the description from the HTML using pcregrep and increased buffer size
description=$(pcregrep --buffer-size=10M -oM '(?<=<meta property="og:description" content=")([^"]*)(?=")' "$tmp_file")

# Remove "&#..." patterns from the description
description=$(echo "$description" | sed 's/&#[^;]*;//g')

# Extract the first line of the description
description_content=$(echo "$description" | awk -F 'Followers' '{print $1}')

# Print the extracted content
echo ""
echo "NAME: $title"
echo ""
echo "FOLLOWER COUNT: $followers"
echo ""
echo "DESCRIPTION: $description_content"
echo ""
# Remove the temporary file
rm "$tmp_file"

