#!/bin/sh

echo "$(figlet Threads-CLI)" 
echo ""
echo "Threads-CLI is a command line tool to grab information about any profile on Threads."
echo ""
echo "- by Amoghavarsha, @TheAmoghavarsha" 
echo ""

echo "Enter the username: "
echo ""
read username


url="https://www.threads.net/@${username}"

tmp_file=$(mktemp)
curl -s "$url" > "$tmp_file"

followers=$(grep -oE '[0-9]+[A-Za-z]* Followers' "$tmp_file" | head -n 1)


title=$(grep -o '<meta property="og:title" content="[^"]*' "$tmp_file" | grep -o '[^"]*$' | sed 's/&#064;//g' | sed 's/ on Threads$//')


description=$(pcregrep --buffer-size=10M -oM '(?<=<meta property="og:description" content=")([^"]*)(?=")' "$tmp_file")


description=$(echo "$description" | sed 's/&#[^;]*;//g')


description_content=$(echo "$description" | awk -F 'Followers' '{print $1}')


echo ""
echo "NAME: $title"
echo ""
echo "FOLLOWER COUNT: $followers"
echo ""
echo "DESCRIPTION: $description_content"
echo ""

rm "$tmp_file"

